#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=14gb
#PBS -l walltime=00:15:00
#PBS -A open
#PBS -o logs/bulk_cross.log.out
#PBS -e logs/bulk_cross.log.err
#PBS -t 1-NSAMPLES

module load gcc
module load samtools
module load anaconda3
source activate my-env

# Cross all BED x all BAM to run some scripts (typically TagPileup)

# Fill in placeholder constants with your directories
WRK=/path/to/20XX-LastName_Journal/
BAMDIR=$WRK/data/BAM
BEDDIR=$WRK/data/BED
OUTDIR=$WRK/OutputLocation

# Setup ScriptManager for job array
ORIGINAL_SCRIPTMANAGER=$WRK/bin/ScriptManager-v0.14.jar
SCRIPTMANAGER=$WRK/bin/ScriptManager-v0.14-$PBS_ARRAYID.jar
cp $ORIGINAL_SCRIPTMANAGER $SCRIPTMANAGER

# Script shortcuts
COMPOSITE=$WRK/bin/sum_Col_CDT.pl

# Set up output directories
cd $WRK
[ -d $OUTDIR ] || mkdir $OUTDIR

# Determine BAM file for the current job array index
BAMFILE=`ls $BAMDIR/*.bam | head -n $PBS_ARRAYID | tail -1`
BAM=`basename $BAMFILE ".bam"`
[ -f $BAMFILE.bai ] || samtools index $BAMFILE

# Process BAM file for each BED file in directory
for BEDFILE in `ls $BEDDIR/*1000bp.bed`;
do
	echo $BEDFILE
	BED=`basename $BEDFILE ".bed"`
	DIR=$OUTDIR/$BED
	[ -d $DIR ] || mkdir $DIR

	# Do stuff here

	# # Example TF Pileup:
	# [ -d $DIR/COMPOSITES ] || mkdir $DIR/COMPOSITES
	# [ -d $DIR/CDT ] || mkdir $DIR/CDT
	# [ -d $DIR/NormComposites ] || mkdir $DIR/NormComposites
	# BASE=$BAM\_$BED\_read1
	# # Pileup
	# java -jar $SCRIPTMANAGER read-analysis tag-pileup $BEDFILE $BAMFILE --cpu 4 -o $DIR/COMPOSITES/$BASE.raw.out -M $DIR/CDT/$BASE.cdt
	# # Scale pileups
	# java -jar $SCRIPTMANAGER read-analysis scale-matrix $DIR/CDT/$BASE\_anti.cdt -s $FACTOR -o $DIR/CDT/$BASE\_anti_Normalized.cdt
	# java -jar $SCRIPTMANAGER read-analysis scale-matrix $DIR/CDT/$BASE\_sense.cdt -s $FACTOR -o $DIR/CDT/$BASE\_sense_Normalized.cdt
	# # Column-wise sum normalized CDTs into composites
	# perl $COMPOSITE $DIR/CDT/$BASE\_anti_Normalized.cdt $DIR/CDT/$BASE\_ANTI
	# perl $COMPOSITE $DIR/CDT/$BASE\_sense_Normalized.cdt $DIR/CDT/$BASE\_SENSE
	# # Merge into same normalized file and remove intermediates
	# cat $DIR/CDT/$BASE\_ANTI <(tail -1 $DIR/CDT/$BASE\_SENSE) > $DIR/NormComposites/$BASE\_Normalized.out
	# rm $DIR/CDT/$BASE\_SENSE $DIR/CDT/$BASE\_ANTI
done
