#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=14gb
#PBS -l walltime=24:00:00
#PBS -A open
#PBS -o logs/run_epitopeid.log.out
#PBS -e logs/run_epitopeid.log.err

module load gcc
module load samtools
module load anaconda3

### CHANGE ME
source activate my-env # load conda environment with GenoPipe dependencies
EPITOPEID=/path/to/GenoPipe/EpitopeID
WRK=/path/to/20XX-LastName_Journal/
###
INPUTFQ=$WRK/data/FASTQ
OUTPUT=$WRK/01_Run_GenoPipe/epitopeid

cd $WRK
[ -d logs ] || mkdir logs
[ -d $OUTPUT ] || mkdir $OUTPUT

cd $EPITOPEID
bash identify-Epitope.sh -i $INPUTFQ -o $OUTPUT -d $EPITOPEID/sacCer3_EpiID -t 6
