#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=14gb
#PBS -l walltime=24:00:00
#PBS -A my-allocation
#PBS -o logs/run_epitopeid.log.out
#PBS -e logs/run_epitopeid.log.err

module load gcc
module load samtools
module load anaconda3
module load bwa
source activate my-env

# REPLACE WITH YOUR PATH
WRK=/path/to/20XX-LastName_Journal/
INPUTFQ=$WRK/data/FASTQ
EPITOPEID=/path/to/GenoPipe/EpitopeID
OUTPUT=$WRK/01_Run_GenoPipe/epitopeid

cd $WRK
[ -d logs ] || mkdir logs
[ -d $OUTPUT ] || mkdir $OUTPUT

cd $EPITOPEID
bash identify-Epitope.sh -i $INPUTFQ -o $OUTPUT -d $EPITOPEID/sacCer3_EpiID -t 6
